## new "vector" spaces

the idea is that a space can be formed if the residents support
linear combination: 

**add them together and/or multiply by scalar
values**

emphasizing on these 2 operations:

- mult a "vector" by a scalar, the result is still in the space
- add two "vectors" together, the result is still in the space


let $M$ by all 3 by 3 matrices

it has the follow subspaces:

$D$ (diagonal), $U$ (upper triangular), $S$ (symmetric)

**what are their basis? what are their dimensions?**

### the basis and dimension of M

one of the basis is

$\left[ A_{11} \right],
\left[ A_{12} \right],
\left[ A_{13} \right],
\dots,
\left[ A_{33} \right]
\\
\left[ A_{11} \right] = \begin{bmatrix}
1 & 0 & 0 \\
0 & 0 & 0 \\
0 & 0 & 0
\end{bmatrix}
$

and the dimension of $M$ is 9, $dimM = 9$


### the basis and dimension of S, U

similarly, $S$ and $U$ only touch "one side" of the diagonal,
therefore

$dimS = 6, dimU = 6$ 

note that the diagonal matrices belong to both $S$ and $U$

### the space of S + U

in the space of $S$ + $U$, an element is the sum of an element of $S$ and an element of $U$

for example $M = S + U$

this space has no particular interesting properties...

the important thing to note is, $S \cup U$ is not $S + U$

### differential equations

showing that linear algebra, particularly space, basis
and dimension and linear combinations play a wider role
than matrix of m x n

#### what is the solution of 2nd order differential equation

$
\frac {d^{2}y} {dx^{2}} + y
= 0
\\
(y'' + y = 0)
$

think in terms of the nullspace of this differential equation and
the special solution is:

$y = cosx, y = sinx$

(which is equivalent to x = $I$)

and the complete solutions are (it does not have a "particular
solution"):

$y = c_{1} \ cosx + c_{2} \ sinx$

which are the combinations

#### what are the basis and dimension

$y = cosx, y = sinx$

$dim = 2$

#### what is linear differential equation about

about finding basis in the solution space of the diff eq

(18.03)

## rank 1 matrices

example

$
A_{2 \ \times \ 3} = 
\begin{bmatrix}
1 & 4 & 5 \\
2 & 8 & 10
\end{bmatrix}
$

its two rows are not independent; the first row (or the second)
is the basis; 

$dimC(A) = 1$, and the pivot column is the first column


I can write this $A$ as:

$
A = \begin{bmatrix} 1 \\ 2 \end{bmatrix}
\begin{bmatrix} 1 & 4 & 5 \end{bmatrix}
$

**in fact, every rank-1 matrix has this form $A = u v^{T}$**

**rank-1 matrices are the building blocks for other matrices;**

**other higher rank matrices can be broken down to the combinations
of rank-1 matrices**

### subset of rank-n matrices

question: can a subset of rank-1 matrices form a subspace?

**no because the combination of rank-1 can ONLY produce rank-2 (which
violates the rules in the beginning: the result
of the combination must still be in the given space);**

however it can not produce higher ranks 3, 4 but only 2



### guess subspace dimension

suppose in $R^{4}$, there is a $v = \begin{bmatrix}
v_{1} \\ v_{2} \\ v_{3} \\ v_{4} \end{bmatrix}$, suppose I take
the subspace of v, 
where $v_{1} + v_{2} + v_{3} + v_{4} = 0$, 

#### question: is it a subspace?

yes, the linear combinations of the multiple of some non-zero v 
will also produce $Z$

let $p$ and $q$ be such two $R^{4}$ vectors:

$
p_{1} + p_{2} + p_{3} + p_{4} = 0 \\
q_{1} + q_{2} + q_{3} + q_{4} = 0 \\
\\
c_{1}(p_{1} + p_{2} + p_{3} + p_{4}) +
c_{2}(q_{1} + q_{2} + q_{3} + q_{4}) = c_{1} \times 0 + c_{2} \times 0
$

#### question: what is the dimiension of this subspace?

recall that a dim of a subspace is the number of vector in
its bases.

consider $v_{1} + v_{2} + v_{3} + v_{4} = 0$ the nullspace
of $Ax = b$, namely $Ax = 0$,

what is $A$?

$A = \begin{bmatrix}1 & 1 & 1 & 1\end{bmatrix}$

and it has a rank of 1

knowing that $dimN(A) = n - r$, the dimension is 3 (4 columns)

#### question: what are its 4 fundamental subspaces?

$dimC(A^{T}) = 1$ (rank is 1)

$dimN(A) = 3$, the basis being the special solutions (using the
3 free variables, as there is only 1 pivot variable)

sanity check: $dimC(A^{T}) + dimN(A) = 4$ (dim = n - r)

$
\begin{bmatrix}-1 \\ 1 \\ 0 \\ 0\end{bmatrix},
\begin{bmatrix}-1 \\ 0 \\ 1 \\ 0\end{bmatrix},
\begin{bmatrix}-1 \\ 0 \\ 0 \\ 1\end{bmatrix}
$

$dimC(A) = 1$, $C(A)$ is row-1 

$dimN(A^{T}) = 0$, which is $Z$ , the zero vector

sanity check: $dimC(A) + dimN(A^{T}) = 1$ (dim = m - r)

## small world graph



what is a graph: 

a set of nodes and edges that connect the nodes

### the interesting qestions about graph

the shortest and the longest path that connects two nodes in a graph

"6 degrees separation"

<https://en.wikipedia.org/wiki/Six_degrees_of_separation>


# Recitation and Exercises


## recitation

show that the set of 2 x 3 matrices $A$ whose
nullspace contains $\begin{bmatrix}2 \\ 1 \\ 1\end{bmatrix}$
is a vector subspace, and find a basis for it

what about the set of those whose column space
contains $\begin{bmatrix}2 \\ 1\end{bmatrix}$,
do they form a vector subspace ??

imagine there are $A, B$

$A \cdot \begin{bmatrix}2 \\ 1 \\ 1\end{bmatrix} = 
\begin{bmatrix}0 \\ 0\end{bmatrix}$

(same equation for $B$...)

their linear combinations also satisfy $(A + B) \begin{bmatrix}2 \\ 1 \\ 1\end{bmatrix} = 0$

$(c A)\begin{bmatrix}2 \\ 1 \\ 1\end{bmatrix} = 0
\\
A \begin{bmatrix}2 \\ 1 \\ 1\end{bmatrix} = \frac {0} {c} = 0$

#### summary: how do we show that a something is a vector subspace?

the linear combination of two vectors in this space is also in
this space

- add two vectors together, the result is still in this space
- mult a vector by a scalar, the result is still in this space


#### what are the bases of nullspace?

let $A$ be $\begin{bmatrix}row_{1} \\ row_{2}\end{bmatrix}$

and each row mult `{2, 1, 1}` is 0

let both rows be `{a, b, c}` then `2a + b + c = 0`

substitute `c` I get:

`{a, b, -2a -b}` which is `{a, 0, -2a} + {0, b, -b}`

turn each row into the linear combination of two vectors

(pulling `a` and `b` out) `a {1, 0, -2) + b {0, 1, -1}` 

finally, putting things back into the matrices form, and
account for row-1, row-2

the basis are:

```
[[1, 0, -2],
 [0, 0, 0 ]]
 
[[0, 1, -1],
 [0, 0, 0]]
 
[[0, 0, 0],
 [1, 0, -2]]
 
[[0, 0, 0],
 [0, 1, -1]]
```

this means the dimension of the subspace is 4

sanity check: does the linear combination premise still hold?

#### given a set of A whose column space contains $\begin{bmatrix}2 \\ 1\end{bmatrix}$ do they form a subspace ?

to check if they form a vector subspace, check if $Z$ is in the
subspace (in this case $Z$ is the **zero matrix** instead of
the zero vector)

**review the definition of vector subspace in 18.06_05 notebook**

also, remember that in order to form a vector subspace, the linear
combination of some A should still be in the subspace, this include
mult A by 0 that produces $Z$

this can also prove that this set of matrices (with a specific
column vector in the column space) DO NOT form a vector subspace


In [21]:
# Problem 11.1

# write the 3 x 3 identity matrix as a combination of the
# other 5 permutation matrices
# then show that those five matrices are linearly
# independent
# assume a combination gives c1P1 + ... + c5P5 = 0 
# and check entries to prove ci is zero

# the given permutation matrices are a basis for the
# subspace of 3 x 3 matrices with row and column
# sums all equal

import numpy as np
import pylinearalgebra.mattools as mt

# I only have 6 perm for a 3x3 matrix,
# I is one of them and is the RHS,
# the other 5 are the LHS
import sympy

I = sympy.Symbol('1')
O = sympy.Symbol('0')

p1 = [
    [I, O, O], #
    [O, O, I], 
    [O, I, O],
]
p2 = [
    [O, O, I], #
    [O, I, O],
    [I, O, O], 
]
p3 = [
    [O, O, I], #
    [I, O, O],
    [O, I, O],
]
p4 = [
    [O, I, O], #
    [I, O, O], 
    [O, O, I],
]
p5 = [
    [O, I, O], #
    [O, O, I],
    [I, O, O],
]

o = p1
for p in [p2, p3, p4, p5]:
    o = np.add(o, p)
print(o)
R, _ = mt.rref(o)
print(R)

[[4*0 + 1 3*0 + 2*1 3*0 + 2*1]
 [3*0 + 2*1 4*0 + 1 3*0 + 2*1]
 [3*0 + 2*1 3*0 + 2*1 4*0 + 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [48]:
# the answer to the second question can be observed
# using sympy again

import sympy
S = sympy.Symbol

c1 = S('c1')
c2 = S('c2')
c3 = S('c3')
c4 = S('c4')
c5 = S('c5')

o = np.multiply(c1, p1)
for c, p in zip([c2, c3, c4, c5], [p2, p3, p4, p5]):
    o = np.add(o, np.multiply(c, p))
for r in o.tolist():
    print(r)


[0*c2 + 0*c3 + 0*c4 + 0*c5 + 1*c1, 0*c1 + 0*c2 + 0*c3 + 1*c4 + 1*c5, 0*c1 + 0*c4 + 0*c5 + 1*c2 + 1*c3]
[0*c1 + 0*c2 + 0*c5 + 1*c3 + 1*c4, 0*c1 + 0*c3 + 0*c4 + 0*c5 + 1*c2, 0*c2 + 0*c3 + 0*c4 + 1*c1 + 1*c5]
[0*c1 + 0*c3 + 0*c4 + 1*c2 + 1*c5, 0*c2 + 0*c4 + 0*c5 + 1*c1 + 1*c3, 0*c1 + 0*c2 + 0*c3 + 0*c5 + 1*c4]


In [25]:
# prove that row(i) = column(i)
for i in range(o.shape[0]):
    print(o[i] == o[:, i])

[ True  True  True]
[ True  True  True]
[ True  True  True]


In [26]:
# Problem 11.2

# M is the space of 3 x 3 matrices

# mult each matrix X in M by 
A = [
    [1, 0, -1],
    [-1, 1, 0],
    [0, -1, 1],
]
# notice that A . {1, 1, 1} = {0, 0, 0}

# a) which matrices X lead to AX = 0 ?

# b) which matrices have the form AX for some matrix X ?

# c) finds the nullspace of the operation AX
#    finds the column space 
#    what are the dim of these two subspaces of M
#    why do the dim add to (n - r) + r = 9


In [49]:
import numpy as np
import pylinearalgebra.mattools as mt

import sympy

S = sympy.Symbol

X = [
    [S('X11'), S('X12'), S('X13')],
    [S('X21'), S('X22'), S('X23')],
    [S('X31'), S('X32'), S('X33')],
]

A = [
    [1, 0, -1],
    [-1, 1, 0],
    [0, -1, 1],
]

AX = np.dot(A, X)
print(AX)

# X11 - X31     X12 - X32     X13 - X33
# X21 - X11     X22 - X12     X23 - X13 
# X31 - X21     X32 - X22     X33 - X23

X_ = [
    [1, 2, 3],
    [1, 2, 3],
    [1, 2, 3],
]
print(np.dot(A, X_))



[[X11 - X31 X12 - X32 X13 - X33]
 [-X11 + X21 -X12 + X22 -X13 + X23]
 [-X21 + X31 -X22 + X32 -X23 + X33]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
