In [14]:
# elimination in python

# 1)

# https://numpy.org/doc/stable/reference/generated/numpy.linalg.solve.html

# 2)

# https://stackoverflow.com/questions/15638650/is-there-a-standard-solution-for-gauss-elimination-in-python

from numpy import array
from scipy.linalg import lu

a = array([
    [2.,4.,4.,4.],
    [1.,2.,3.,3.],
    [1.,2.,1.,2.],
    [1.,4.,3.,4.],
])

pl, u = lu(a, permute_l=True)
print(pl)
print(u)

# u is the form after gaussian elimination

[[ 1.   0.   0.   0. ]
 [ 0.5  0.  -1.   1. ]
 [ 0.5  0.   1.   0. ]
 [ 0.5  1.   0.   0. ]]
[[ 2.  4.  4.  4.]
 [ 0.  2.  1.  2.]
 [ 0.  0. -1.  0.]
 [ 0.  0.  0.  1.]]


### forward elimination

the diagonal elements in a matrix are its pivot

the result of forward elimination is $U$, the upper triangular

the RHS is called $c$


### the pivot

pivot can not be zero, otherwise the matrix is singular and invertible


### back substitution




### elimination expressed as matrices

to eliminate the second row:

$\begin{align}
\begin{bmatrix}
1 & 0 & 0 \\
-3 & 1 & 0 \\
0 & 0 & 1
\end{bmatrix}
\begin{bmatrix}
1 & 2 & 1 \\
3 & 8 & 1 \\
0 & 4 & 1
\end{bmatrix}
=
\begin{bmatrix}
1 & 2 & 1 \\
0 & 2 & -2 \\
0 & 4 & 1 
\end{bmatrix}
\\
U = E_{21} \ M
\end{align}$

$E_{21}$ is the elementary or elimination matrix for the second row

I will need another matrix $E_{32}$ for the 3rd row

$U = E_{32} \ (E_{21} \ A)$

using the associative law (but note that **commutative law is false**!)

$U = (E_{32} \ E_{21}) \ A$

In [20]:
# row operation: exchange rows
# P . A

import numpy as np
A = np.array([
    [1, 2],
    [3, 4],
])

np.dot(np.array([[0, 1], [1, 0]]), A)

array([[3, 4],
       [1, 2]])

In [23]:
# 3-D matrix

import numpy as np
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])

np.dot(np.array([[0, 0, 1], [0, 1, 0], [1, 0, 0]]), A)

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [25]:
# arbitrary order

import numpy as np
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])

np.dot(np.array([[0, 0, 1], [1, 0, 0], [0, 1, 0]]), A)

array([[7, 8, 9],
       [1, 2, 3],
       [4, 5, 6]])

In [1]:
# column operation: exchange columns
# A . P

import numpy as np
A = np.array([
    [1, 2],
    [3, 4],
])

np.dot(A, np.array([[0, 1], [1, 0]]))

array([[2, 1],
       [4, 3]])