### permutations, transpose and then, the real beginning of linear algebra

to see the pictures of vector space - not just vectors but space of
vectors

and see the subspace of those space


### permutations

$P$, to execute row exchanges (if a zero shows up in the pivot
position, I move it away)

but what happens to $A = LU$ ??

in this case the $P$ is $I$

Matlab would do row exchanges when the value in the pivot position
is close to zero - the theory does not require row exchanges in this
situation but for the sake of numeric precision, it does it anyway

$PA = LU$


#### what is permutation anyway?

$P$ is $I$ with reordered rows ($I$ being the "do nothing" $P$)

source: <https://en.wikipedia.org/wiki/Permutation_matrix>

the total number of possible $P$ is $n!$

also note that a single $P$ can reorder a few rows


#### the properties of permutation

$P^{-1} = P^{T}$


$P^{T}P = I$


In [4]:
# permutation matrix and row exchange

# source:
# https://stackoverflow.com/questions/34438098/permute-rows-and-columns-of-a-matrix
# You can perform the swap in a one-liner using integer array indexing:

import numpy as np

A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(A)
A[[0, 1, 2]] = A[[2, 0, 1]]
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[7 8 9]
 [1 2 3]
 [4 5 6]]


### transpose

$\begin{bmatrix}1 & 3 \\ 2 & 3 \\ 4 & 1\end{bmatrix}^{T} = 
\begin{bmatrix}1 & 2 & 4 \\ 3 & 3 & 1\end{bmatrix}$

generalized to 

$A^{T}_{ij} = A_{ji}$


#### symmetric matrices 

$A^{T} = A$

$AA^{T}$ is a symmetric matrix, proof

$(AA^{T})^{T} = (A^{T})^{T}A^{T} = AA^{T}$

In [12]:
import numpy as np

# source:
# https://numpy.org/doc/stable/reference/generated/numpy.matrix.transpose.html

A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])

At = np.matrix.transpose(A)
print(A)
print(At)



[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


### vector spaces




#### what is vector space?

to (legitmately) talk about a space of vectors, we must be able
to add the vectors, multiply them by numbers plus some rules

examples: $R^{2}$, all 2-D vectors (vectors with 2 real components)

$\begin{bmatrix} 3 \\ 2 \end{bmatrix} \,
\begin{bmatrix} 0 \\ 0 \end{bmatrix} \,
\begin{bmatrix} \pi \\ e \end{bmatrix} \, \dots
$

$R^{2}$ is the X-Y plane

$R^{n}$ is typically made a column vector


#### closed or not closed

"closed under multiplication by all the real numbers"


#### a vector space inside R2, a subspace

once I have a vector that goes through (0, 0) in R2, 
I can multiply that vector by any number 
to form an entire line, that is a subspace




#### all subspaces of R2

1) R2 itself

2) any line going through (0, 0)

3) (0, 0) alone, subspace $Z$




#### all subspaces of R3

1) R3 itself

2) zero vector $Z$

3) a plane through the origin

4) a line through the origin



### expressing subspace in matrix form

given $A$ representing $R^{3}$

1) $A$

2) the $Z$, zero vector: $\begin{bmatrix}0 \\ 0 \\ 0\end{bmatrix}$

3) all the linear combinations (multiplying by nums; adding) of the
columns of $A$; this is the **column space**, $C(A)$, a plane

4) all the linear combinations of a single column of $A$, a line



extending this to $R^{10}$

take the linear combinations of 5 columns of $A_{10 \times 10}$ to
create a subspace of $R^{10}$

# Recitation and Exercises

In [ ]:
# problem 5.1

[
    [1, 0, 0],
    [0, 0, 1],
    [0, 1, 0]
]