### multiplication

source of latex:
<https://www.overleaf.com/learn/latex/Integrals,_sums_and_limits>

#### method 1: standard row x colume operation

$A \ B = C$

$\begin{align}
C_{ij} = row_{i} of A \cdot column_{j} of B
\\
C_{ij} = a_{i1} b_{1j} + a_{i2} b_{2j} + \dots + a_{in} b_{nj}
\\
\sum_{k=1}^{n} a_{ik} b_{kj}
\\
\\
shapes: A_{m \times n} \ B_{n \times p} = C_{m \times p}
\end{align}$



#### method 2: thinking in terms of columns

$\begin{align}
A \ B = C
\\
A \ \begin{bmatrix}c_{1} & c_{2} & \dots & c_{n} \end{bmatrix} = 
\begin{bmatrix}A c_{1} & A c_{2} & \dots & A c_{n} \end{bmatrix}
\end{align}$

break down the problem into several problems $A c_{n}$ 

i.e. C is the combination of $A c_{n}$


#### method 3: thinking in terms of rows




In [1]:
# calculate the inverse of an invertible matrix M

import numpy as np
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [0, 8, 9],
])
A_ = np.linalg.inv(A)
print(A_)
I = np.dot(A, A_)
print(I)

[[-0.14285714  0.28571429 -0.14285714]
 [-1.71428571  0.42857143  0.28571429]
 [ 1.52380952 -0.38095238 -0.14285714]]
[[1.00000000e+00 0.00000000e+00 5.55111512e-17]
 [0.00000000e+00 1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
