In [2]:
# elimination in python

# 1)

# https://numpy.org/doc/stable/reference/generated/numpy.linalg.solve.html

# 2)

# https://stackoverflow.com/questions/15638650/is-there-a-standard-solution-for-gauss-elimination-in-python

from numpy import array
from scipy.linalg import lu

a = array([[2.,4.,4.,4.],[1.,2.,3.,3.],[1.,2.,2.,2.],[1.,4.,3.,4.]])

pl, u = lu(a, permute_l=True)
print(pl)
print(u)

# u is the form after gaussian elimination

[[1.  0.  0.  0. ]
 [0.5 0.  1.  0. ]
 [0.5 0.  0.  1. ]
 [0.5 1.  0.  0. ]]
[[2. 4. 4. 4.]
 [0. 2. 1. 2.]
 [0. 0. 1. 1.]
 [0. 0. 0. 0.]]
