### multiplication

source of latex:
<https://www.overleaf.com/learn/latex/Integrals,_sums_and_limits>

#### method 1: standard row x colume operation

$A \ B = C$

$\begin{align}
C_{ij} = row_{i} of A \cdot column_{j} of B
\\
C_{ij} = a_{i1} b_{1j} + a_{i2} b_{2j} + \dots + a_{in} b_{nj}
\\
\sum_{k=1}^{n} a_{ik} b_{kj}
\\
\\
shapes: A_{m \times n} \ B_{n \times p} = C_{m \times p}
\end{align}$



#### method 2: thinking in terms of columns

$\begin{align}
A \ B = C
\\
A_{m \times n} \ \begin{bmatrix}c_{1} & c_{2} & \dots & c_{p} \end{bmatrix} = 
\begin{bmatrix}A c_{1} & A c_{2} & \dots & A c_{p} \end{bmatrix}
\end{align}$

break down the problem into several problems $A c_{p}$ 

i.e. C is the combination of $A c_{p}$


#### method 3: thinking in terms of rows

$\begin{align}
\begin{bmatrix}
r_{1} \\ r_{2} \\ \dots \\ r_{m}
\end{bmatrix}
\ \begin{bmatrix}
\dots \\ \dots \\ \dots
\end{bmatrix}
= \begin{bmatrix}
\dots \\ \dots \\ \dots
\end{bmatrix}
\end{align}$

rows in C are the combination of rows of B

#### method 4: thinking in terms of column x rows

$$
A_{m \times 1} \ B_{1 \times p} = C_{m \times p}
$$

C is the multiple of the column matrix A and is also the
multiple of row matrix B;

$$
A \ B = \text{Sum of col of A times row of B}
\\
\begin{bmatrix}
2 & 7 \\ 3 & 8 \\ 4 & 9
\end{bmatrix}
\ \begin{bmatrix}
1 & 6 \\ 0 & 0
\end{bmatrix}
=
\begin{bmatrix}
2 \\ 3 \\ 4
\end{bmatrix} \ \begin{bmatrix}1 & 6\end{bmatrix} 
+ \begin{bmatrix}
2 \\ 3 \\ 4
\end{bmatrix} \ \begin{bmatrix}0 & 0\end{bmatrix} 
+ \dots
$$


for this specially simplified case

$$
\begin{bmatrix}2 \\ 3 \\ 4\end{bmatrix} \
\begin{bmatrix}1 & 6\end{bmatrix} = 
\begin{bmatrix}
2 & 12 \\ 2 & 18 \\ 4 & 24
\end{bmatrix}
$$



all of the rows of C lay on a line of `[1, 6]` - the row space - as they are the multiple of `[1, 6]`; they are in the same direction

similarily, all the columns of C is the multiple of 
$\begin{bmatrix}2 \\3 \\ 4\end{bmatrix}$ hence they lay on
the line of `[2, 3, 4]`

#### block multiplication 

$\begin{align}
\begin{bmatrix}A_{1} & A_{2} \\ A_{3} & A_{4}\end{bmatrix}
\ \begin{bmatrix}B_{1} & B_{2} \\ B_{3} & B_{4}\end{bmatrix}
= \begin{bmatrix}
A_{1} \ B_{1} + A_{2} \ B_{3} & A_{2} \ B_{2} + \dots \\ 
A_{3} \ B_{3} + \dots & A_{4} \ B_{4} + \dots \end{bmatrix}
\end{align}$

think of block multiplication as a generalised rule (derived from
method 1) 



### Inverse

$A^{-1} \ A = A \ A^{-1} = I$


A must be a square matrix (see the wiki link below)


#### when A is not invertible, i.e. singular

$\begin{align}
A = \begin{bmatrix}
1 & 3 \\ 2 & 6
\end{bmatrix}
\end{align}$

**using the column way of thinking (method 3 above)**, all the columns of A lay on the same line (they are the multiples of `[1, 2]`) 

therefore there is no way one can produce an $I$ (where all
the columns lay on different lines) from it


**A is not invertible when I can find a non-zero vector X** that 
makes this possible: $A \ x = 0$



#### find the inverse

example using a 2x2, $A \ A^{-1} = I$

$\begin{align}
\begin{bmatrix}1 & 3 \\2 & 7\end{bmatrix}
\ 
\begin{bmatrix}a & c \\b & d\end{bmatrix}
= 
\begin{bmatrix}1 & 0 \\0 & 1\end{bmatrix}
\end{align}$

the first column is the product of A and the first column of B, see
method 2 above; similar for the second column

therefore the result is to solve two systems

**A times col j of A-inv is the col j of the identity**

this was what Gauss discovered


#### Gauss-Jordan idea

source:
<https://en.wikipedia.org/wiki/Gaussian_elimination#Finding_the_inverse_of_a_matrix>

to solve two equations at once

$\begin{align}
\begin{bmatrix}1 & 3 \\ 2 & 7\end{bmatrix} \ 
\begin{bmatrix}a \\ b\end{bmatrix}
= \begin{bmatrix}1 \\ 0\end{bmatrix}
\\
\begin{bmatrix}1 & 3 \\ 2 & 7\end{bmatrix} \ 
\begin{bmatrix}c \\ d\end{bmatrix}
= \begin{bmatrix}0 \\ 1\end{bmatrix}
\end{align}$

it again uses the idea of augmented matrix

use Gaussian elimination and turn $AI$ into $IA^{-1}$

why Gauss-Jordan idea works? (from wiki)

> One can think of each row operation as the left product by an elementary matrix. Denoting by B the product of these elementary matrices, we showed, on the left, that BA = I, and therefore, B = A−1. On the right, we kept a record of BI = B, which we know is the inverse desired. This procedure for finding the inverse works for square matrices of any size. 

elementry matrix:
<https://en.wikipedia.org/wiki/Elementary_matrix>

$E \ (A \ I) = I \ ?$

because $E \ A$ is $I$, $E$ essentially is $A^{-1}$ and $E \ I$ 
becomes the A-inverse

In [1]:
# calculate the inverse of an invertible matrix M

import numpy as np
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [0, 8, 9],
])
A_ = np.linalg.inv(A)
print(A_)
I = np.dot(A, A_)
print(I)

[[-0.14285714  0.28571429 -0.14285714]
 [-1.71428571  0.42857143  0.28571429]
 [ 1.52380952 -0.38095238 -0.14285714]]
[[1.00000000e+00 0.00000000e+00 5.55111512e-17]
 [0.00000000e+00 1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
